employee-tesk-management/Controllers/UserTaskController.cs
using employee_tesk_management.CustomAttributes;
using employee_tesk_management.Data;
using employee_tesk_management.HelperServices;
using employee_tesk_management.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace employee_tesk_management.Controllers
{

    public class UserTaskController : Controller
    {
        private readonly ILogger<UserTaskController> _logger;
        private readonly AppDbContext _db;
        private Employee _ActiveUser => SessionServices.GetSession(HttpContext);
        public UserTaskController(AppDbContext db, ILogger<UserTaskController> logger) 
        {
            _db = db;
            _logger = logger;
        }
        public IActionResult TaskList()
        {
            try
            {
                VMEmpData empData = new VMEmpData();
                empData.EmployeeList=_db.Employees.Where(x=>x.IsDeleted==false).ToList();
                empData.TaskList= _db.Record.Include(x=>x.Employee).OrderByDescending(x => x.CreatedDate).ToList();
                ViewBag.EmployeeList =new SelectList(empData.EmployeeList,"Id","Name");
                return View(empData);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "error");
                return RedirectToAction("Error", "Error");
            }
        }
        public IActionResult ToDayTaskNew()
        {
            try
            {
                VMEmpData empData = new VMEmpData();
                empData.EmployeeList = _db.Employees.Where(x=>x.IsDeleted==false).ToList();
                empData.TaskList = _db.Record.Include(x=>x.Employee).OrderByDescending(x => x.CreatedDate).ToList();

                return View(empData);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "error");
                return RedirectToAction("Error", "Error");
            }
        }

        [UserAuthorizationAttribute]
        public IActionResult EmployeeTask()
        {
            try
            {
                VMEmpData empData = new VMEmpData();
                DateTime currentDateTime = DateTime.Now;
                string formatedDate = currentDateTime.ToString("MM/dd/yyyy");
                List<Record> records = _db.Record.Where(x => x.EmployeeID == _ActiveUser.Id).ToList();
                empData.CanAddTask = true;
                foreach (var data in records)
                {
                    if (data.CreatedDate.ToString("MM/dd/yyyy").ToString() == formatedDate)
                    {
                        empData.CanAddTask = false;
                        break;
                    }
                }
                empData.EmployeeID = _ActiveUser.Id;
                empData.EmployeeName = _ActiveUser.Name;
                empData.EmployeeEmail = _ActiveUser.Email;
                empData.TaskList = _db.Record.Where(x => x.EmployeeID == _ActiveUser.Id).OrderByDescending(x=>x.CreatedDate).ToList();
                empData.EmployeeList = _db.Employees.Where(x => x.Id == _ActiveUser.Id).ToList();
                return View(empData);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "error occured while loading data");
                return RedirectToAction("Error","Error");
            }
            
        }

        public IActionResult addTask(Record record) 
        {
            try
            {
                Record recData = new Record();
                recData.Task = record.Task;
                recData.CreatedDate = DateTime.Now;
                recData.EmployeeID = _ActiveUser.Id;
                _db.Record.Add(recData);
                _db.SaveChanges();
                return RedirectToAction("EmployeeTask");
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "error");
                return RedirectToAction("Error","Error");
            }
         

        }

        public IActionResult editTask(Record record)
        {
            
            try
            {
                Record oldData = _db.Record.Find(record.Id);
                oldData.Task = record.Task;

                _db.SaveChanges();
                return RedirectToAction("EmployeeTask");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "error");
                return RedirectToAction("Error","Error");
            }
            
        }

        public IActionResult deleteTask(int taskID) 
        {
            try
            {
                Record data = _db.Record.Find(taskID);
                _db.Record.Remove(data);
                _db.SaveChanges();
                return RedirectToAction("EmployeeTask");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "error");
                return RedirectToAction("Error", "Error");
            }
            
        }

        public IActionResult UserDetail(int id)
        {
            try
            {
                var empDetail = _db.Employees.Include(x => x.Records).FirstOrDefault(x => x.Id == id);
                return View(empDetail);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occured while returing user details");
                return RedirectToAction("Error", "Error");
            }
           
        }

        public IActionResult toDayTask()
        {
            try
            {
                var emplist = _db.Employees.Where(x => x.IsDeleted == false).ToList();
                var nowDate = DateTime.Now;
                List<Record> records = _db.Record.Where(x => x.CreatedDate.Date == nowDate.Date).ToList();
                foreach (var item in emplist)
                {
                    var rec = records.FirstOrDefault(x => x.EmployeeID == item.Id);
                    item.Records.Add(rec == null ? new Record() : rec);
                }
                
                return View(emplist);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occured while loading employee task");
                return RedirectToAction("Error", "Error");
            }
            

        }
    }
}

employee-tesk-management/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Tesk Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    @* <link href="~/css/sidebar.css" rel="stylesheet" /> *@
    @* <link rel="stylesheet" href="~/employee_tesk_management.styles.css" asp-append-version="true" /> *@

</head>
<body>
    <div style="height: 100vh; background-color: rgba(0, 0, 0, 0.7);z-index:99" class="position-fixed w-100 d-none " id="blurBox">
        <div class="position-relative d-flex h-100 w-100 justify-content-center align-items-center">
            <div id="addDataFormBox" class="position-absolute d-none p-4 bg-white w-50 rounded">
                <div class="d-flex justify-content-end">
                    <button id="closeAddPopUpBtn" class="btn btn-danger">
                        close
                    </button>
                </div>
                <p class="text-dark fw-bold fs-5">Today's Task</p>
                <form id="addTaskForm" method="POST" class="w-100">
                    <textarea class="form-control" id="summernote" name="Task" rows="3"></textarea>
                    <p class="text-danger" id="emptyAddTaskInputFiled"></p>
                    <div class="d-flex justify-content-end">
                        <button id="addTodayTask" class="btn btn-success mt-3 w-25">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container mb-4">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand">TASK<span style="color:#1450A3">TALLY</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="UserTask" asp-action="EmployeeTask">Task</a>
                        </li>
                    </ul>
                </div>               
                <nav>
                    <div class="collapse navbar-collapse ">
                        <ul class="navbar-nav">
                            <li class=" btn btn-black nav-item dropdown">
                                
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                                    </svg>
                                    <span class="ms-1 align-texttop">Login</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li> <a class="dropdown-item" asp-area="" asp-controller="Employee" asp-action="ChangeEmployeePassword">Password Change</a></li>
                                    <li> <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a></li>

                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
        </nav>

    </div>

    

    @* <div class="container">
    <main role="main" class="pb-3"> *@
    @RenderBody()
    @*    </main>
    </div>
    *@
    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - employee_tesk_management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="
https://cdn.jsdelivr.net/npm/jquery-validation@1.20.0/dist/jquery.validate.min.js
"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>